name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract
      run: Expand-Archive ngrok.zip

    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Open port 28015 UDP
      run: New-NetFirewallRule -DisplayName "Open port 28015 UDP" -Direction Inbound -Protocol UDP -LocalPort 28015 -Action Allow

    - name: Open port 28016 TCP
      run: New-NetFirewallRule -DisplayName "Open port 28016 TCP" -Direction Inbound -Protocol TCP -LocalPort 28016 -Action Allow

    - name: Open port 28017 UDP
      run: New-NetFirewallRule -DisplayName "Open port 28017 UDP" -Direction Inbound -Protocol UDP -LocalPort 28017 -Action Allow

    - name: Open port 28082 TCP
      run: New-NetFirewallRule -DisplayName "Open port 28082 TCP" -Direction Inbound -Protocol TCP -LocalPort 28082 -Action Allow

    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
